### ISSUE TITLE
Error al intentar obtener la información desde el sitio de MPESO.

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/node-tuc#7]
`
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (/home/polin/github/nodenica/node-tuc/lib/tuc.js:89:25)
    at Request.self.callback (/home/polin/github/nodenica/node-tuc/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/polin/github/nodenica/node-tuc/node_modules/request/request.js:978:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/polin/github/nodenica/node-tuc/node_modules/request/request.js:929:12)
    at emitNone (events.js:91:20)
`

**Comment by paulomcnally** [comment]
Solved! https://github.com/nodenica/node-tuc/commit/656ec51b9e7f99b5e8a70a2793705cc163e2753b
